import React from 'react'
import WhyWe from '../components/About/whywe';

export const metadata = {
    title: "About",
    description: "Generated by create next app",
    keywords: "react, web development",
    author: "Your Name",
    // viewport: "width=device-width, initial-scale=1.0",
};

function page() {
  return (
    <WhyWe  />
  )
}

export default page
