import React from 'react'
import WhyWe from '../components/About/whywe';
import Industries from '../components/Home/industries';

export const metadata = {
    title: "About",
    description: "Generated by create next app",
    keywords: "react, web development",
    author: "Your Name",
    // viewport: "width=device-width, initial-scale=1.0",
};

function page() {
  return (
    <>
    <Industries />
    </>
   
  )
}

export default page
